spring:
  datasource:
    url: jdbc:postgresql://192.168.1.253:5432/angular
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update